### PR TITLE
fix: Fixed mobile menu and pt-br page updated

### PR DESCRIPTION
**Pull request by JoaoP-Vieira**
-Mobile menu row to column orientation;
-Support for no-JavaScript browser;
-pt-BR page updated (Ready for translate?).

### CODE REVIEW

**Comment by takusuman** [comment]
Sorry for not viewing it before, I was working in the distribution...

> -Mobile menu row to column orientation;

That sounds awesome!

> -Support for no-JavaScript browser;

Great! I was trying to do a website that didn't broke on ELinks, Lynx or w3m from the beginning.
Some folks who are doing NoSurf often use browsers without full JS support or even text-based ones (I used w3m when I was NoSurfing around the end of 2019).

> -pt-BR page updated (Ready for translate?).

Pretty much, I think. :^)

Thanks a lot, @JoaoP-Vieira.

**Comment by JoaoP-Vieira** [comment]
> Great! I was trying to do a website that didn't broke on ELinks, Lynx or w3m from the beginning. Some folks who are doing NoSurf often use browsers without full JS support or even text-based ones (I used w3m when I was NoSurfing around the end of 2019).

Ok, I'll remember this.

>Thanks a lot, @JoaoP-Vieira.

I believe in the future of this distribution, I'll do whatever I can to help.

**Comment by takusuman** [comment]
Thanks for the support, seriously. We appreciate that we're building a community. 🥲

Without wanting to take advantage of your good will, could you (or you know someone who could) help translate the website?
There's already a partially translated `indexpt.html` (https://github.com/Projeto-Pindorama/copacabana-www/blob/70854e487634635b6752bb915d6a6d26088e1ee5/indexpt.html), but there's a lot of new text to translate.

Also, do you know someone who can host the website (and Silicon Tabula along with Pindorama main website)? Our current webmaster won't be able to serve our website anymore since he will be without the server up in next weeks.
I already have a "plan C" (which is hosting in GitHub) just in case of we don't get a new server (that's because of our custom domain + subdomains), so we won't be completely out of the internet.

PS: Sorry for not responding before, my internet service got down for some days.

**Comment by JoaoP-Vieira** [comment]
Man I already translate some good parts of the Gentoo Handbook to pt-BR, my translations isn't the best but i can help in general.

I would like to continue collaborating on the project, not only on the website but also on the distribution in general, if you need me to test or compile something on my machine.

Add me on Discord so we can talk more, in Portuguese, please. kkkkkk
My Discord: Jusé#8314

**Comment by takusuman** [comment]
> I would like to continue collaborating on the project, not only on the website but also on the distribution in general, if you need me to test or compile something on my machine.

Currently I'm needing to cross-compile to ARM and i486, also needing to finish the documentation.

I sent you a friend request on Discord.

**Pull request merged**
